import { store } from '~/store';
import { attach as _attach, unattach as _unattach } from './attach';
import _add from './add';
import _clear from './clear';
import _state from './state';
import _control from './control';
import _options from './options';
import _on from './on';
import _exit from './exit';
import _spawn from './spawn';

export const attach = _attach.bind(null, store);
export const unattach = _unattach.bind(null, store);
export const add = _add.bind(null, store);
export const clear = _clear.bind(null, store);
export const state = _state.bind(null, store);
export const on = _on.bind(null, store);
export const options = _options.bind(null, store);
export const control = _control.bind(null, store);
export const exit = _exit.bind(null, store);
export const spawn = _spawn.bind(null, store);
